snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(league_name string)"
return_type = "string"
file = "app.zip"
name = "league_fixtures_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "SI_DB"
schema = "HARMONIZED"
warehouse = "SI_WH"
role = "SI_ROLE"
overwrite = true
