USE ROLE SI_ROLE;
USE WAREHOUSE SI_WH;
USE DATABASE SI_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE LEAGUES  (
  LEAGUE_ID NUMBER(2),
  NAME VARCHAR(100)
);

INSERT INTO LEAGUES(LEAGUE_ID,NAME)
VALUES
(1,'Premier League'),(2,'La Liga'),(3,'Serie A Brasil');

CREATE OR REPLACE TABLE TEAMS  (
  TEAM_ID NUMBER(2),
  NAME VARCHAR(100)
);

INSERT INTO TEAMS(TEAM_ID,NAME)
VALUES
(1,'Arsenal'),(2,'Real Madrid'),(3,'Chelsea'),(4,'Santos'),(5,'Corinthians'),(6,'Liverpool'), (7,'Manchester City'), (8,'Barcelona');


CREATE OR REPLACE TABLE LEAGUE_TEAMS (
    TEAM_ID NUMBER(2),
    LEAGUE_ID NUMBER(2)
);

INSERT INTO LEAGUE_TEAMS (TEAM_ID, LEAGUE_ID)
VALUES (1,1), (2,2), (3,1), (4,3),(5,3),(6,1),(7,1),(8,2);


CREATE OR REPLACE TABLE FIXTURES (
    FIXTURE_ID NUMBER(2),
    LEAGUE_ID NUMBER(2),
    HOME_TEAM_ID NUMBER(2),
    AWAY_TEAM_ID NUMBER (2),
    HOME_TEAM_GOALS NUMBER(2),
    AWAY_TEAM_GOALS NUMBER (2),
    FIXTURE_DATE DATE
);

INSERT INTO FIXTURES (FIXTURE_ID,LEAGUE_ID,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_TEAM_GOALS,AWAY_TEAM_GOALS,FIXTURE_DATE)
VALUES
(1,1,7,1,2,1,CURRENT_DATE()),
(2,1,1,3,4,0,CURRENT_DATE()),
(3,1,1,7,3,2,CURRENT_DATE()),
(4,1,1,6,0,0,CURRENT_DATE())
;

